service: espipe

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**
   - ./etc/**

functions:
  index:
    handler: bin/index
    events:
      - http:
          path: espipe
          method: post
  flush:
    handler: bin/flush
    events:
      - schedule: rate(5 seconds)